version: '3'
services:
  telegrammonitorbot:
    image: telegrammonitorbot
    container_name: TelegramMonitorBot
    hostname: "{{.Node.Hostname}}"
    volumes:
      - /etc/hostname:/etc/hostname
      - /proc:/proc_host
      - /sys:/sys
    build:
      context: .
