version: '3'
services:
  telegrammonitorbot:
    image: agonbar/telegrammonitorbot:latest
    hostname: "{{.Node.Hostname}}"
    volumes:
      - /path/to/config.json:/config.json
      - /proc:/host/proc
      - /sys:/host/sys
      - /etc:/host/etc
      - /var:/host/var
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
      - HOST_VAR=/host/var
    deploy:
      mode: global